version: "2.2"

services:
  repl:
    links:
      - testrpc
      - postgres:db
    extends:
      file: ./docker-compose-base.yml
      service: dev-base
    command: lein repl-dev

  test-watch:
    extends:
      file: ./docker-compose-base.yml
      service: test-base
    links:
      - testrpc
      - postgres-test:db
    command: lein test-refresh

  test:
    extends:
      file: ./docker-compose-base.yml
      service: test-base
    links:
      - testrpc
      - postgres-test:db
    command: lein test

  testrpc:
    image: parity/parity:v1.9.5
    cpus: 0.5
    volumes:
      - testrpc-chain:/root/.local/share/io.parity.ethereum
    command: --chain kovan --unsafe-expose --no-warp --tracing on

  postgres:
    image: postgres:10.3-alpine
    environment:
      - POSTGRES_PASSWORD:pass

  postgres-test:
    image: postgres:10.3-alpine
    environment:
      - POSTGRES_PASSWORD:pass

volumes:
  testrpc-chain:
