version: "2.2"

services:
  build-base:
    image: clojure:lein-2.8.1
    volumes:
      - ./:$PWD
    working_dir: $PWD
    environment:
      - HOST=0.0.0.0
      - DATABASE_URL=jdbc:postgresql://db/postgres?user=postgres&password=pass
      - JSONRPC_URL=https://kovan.infura.io/${INFURA_TOKEN}

  dev-base:
    extends:
      service: build-base
    ports:
      - "7000:7000"
      - "3000:3000"
      - "9229:9229"

  test-base:
    extends:
      service: build-base
