version: "2.2"

services:
  repl:
    links:
      - postgres:db
    extends:
      file: ./docker-compose-base.yml
      service: dev-base
    command: lein repl-dev

  test-watch:
    extends:
      file: ./docker-compose-base.yml
      service: test-base
    links:
      - postgres-test:db
    command: lein test-refresh

  test:
    extends:
      file: ./docker-compose-base.yml
      service: test-base
    links:
      - postgres-test:db
    command: lein test

  postgres:
    image: postgres:10.3-alpine
    environment:
      - POSTGRES_PASSWORD:pass

  postgres-test:
    image: postgres:10.3-alpine
    environment:
      - POSTGRES_PASSWORD:pass

volumes:
  jsonrpc_url-chain:
